services:
  my-magic-portfolio:
    build:
      dockerfile: Dockerfile
    image: magic-portfolio/my-magic-portfolio:latest # keep this setting for automatically refreshing docker
    container_name: my-magic-portfolio # keep this setting for automatically refreshing docker
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tai.vnpsc.com,www.tai.vnpsc.com,astropop.top,www.astropop.top
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=tai.vnpsc.com,www.tai.vnpsc.com,astropop.top,www.astropop.top
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
    networks:
      shared:
        aliases:
          - my-magic-portfolio
    restart: always
networks:
  shared:
    external: true
    name: my_tailt_shared_net
